### PR TITLE
HLC implementation

### PR DESCRIPTION
**Pull request by GiulioRossetti**
Pull request tied to issue #239.

@seoanezonjic, thanks for the integration effort!

### CODE REVIEW

**Comment by GiulioRossetti** [comment]
All checks have passed.

I noticed that `hierarchical_link_community_full` method definition in edge_clustering.py does not have the docstring describing the method and its parameter (needed to generate the online documentation).

@seoanezonjic could you add it in a commit in your fork? The PR will update automatically.

**Comment by seoanezonjic** [comment]
Docstring added to hierarchical_link_community_full method

**Comment by seoanezonjic** [comment]
@GiulioRossetti do you need something else? I'm not sure if the last commit has passed the checks needed to integrate my last commit.

**Comment by GiulioRossetti** [comment]
Merged 👍 
I just have to link the methods in the documentation. Thanks' again!

**Pull request merged**
